<a href="https://colab.research.google.com/github/zhanna-naumenko/DI-Bootcamp/blob/main/W6D1_ExercisesXP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 1**

In [3]:
import numpy as np

user_array = np.arange(0, 10)
print(user_array)

[0 1 2 3 4 5 6 7 8 9]


**Exercise 2**

In [5]:
my_list = [3.14, 2.17, 0, 1, 2]
list_array = np.array(my_list, dtype=np.int64)
print(list_array)

[3 2 0 1 2]


**Exercise 3**

In [8]:
array_new = np.arange(1, 10).reshape(3, 3)
print(array_new)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Exercise 4**

In [23]:
random_array = (np.random.rand(4, 5)).round(2)
print(random_array)

[[0.98 0.83 0.27 0.28 0.66]
 [0.48 0.59 0.49 0.49 0.86]
 [0.35 0.09 0.41 0.95 0.36]
 [0.72 0.51 0.02 0.55 0.36]]


**Exercise 5**

In [24]:
print(random_array[1])

[0.48 0.59 0.49 0.49 0.86]


**Exercise 6**

In [31]:
given_array = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
revers = np.flipud(given_array)
print(revers)
print(given_array[::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


**Exercise 7**

In [32]:
array_ident = np.identity(4)
print(array_ident)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Exercise 8**

In [34]:
sum_array = np.sum(user_array)
av_array = np.average(user_array)
print(f"Sum of array: {sum_array}")
print(f"Averag of array: {av_array}")

Sum of array: 45
Averag of array: 4.5


**Exercise 9**

In [37]:
array_line = np.arange(1, 21).reshape((4, 5))
print(array_line)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**Exercise 10**

In [38]:
odd_array = user_array[user_array % 2 == 1]
print(odd_array)

[1 3 5 7 9]
