**Exercise 1 : Array Creation and Manipulation**

In [2]:
import pandas as pd
import numpy as np

In [17]:
arr1 = np.arange(10)
print(f"array {arr1}")

array [0 1 2 3 4 5 6 7 8 9]


**Exercise 2 : Type Conversion and Array Operations**

In [5]:
list_to_array = [3.14, 2.17, 0, 1, 2]
arr2 = np.array(list_to_array, dtype=int)
print(f"array {arr2}")

array [3 2 0 1 2]


**Exercise 3 : Working with Multi-Dimensional Arrays**

In [6]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"2D array: {matrix}")
print(f"Type: {type(matrix)}")
print(f"Shape: {matrix.shape}")

2D array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type: <class 'numpy.ndarray'>
Shape: (3, 3)


**Exercise 4 : Creating Multi-Dimensional Array with Random Numbers**

In [9]:
arr3 = np.random.rand(4,5)
arr3 = np.round(arr3, 2)
print(arr3)

[[0.63 0.11 0.81 0.58 0.88]
 [0.83 0.45 0.53 0.89 0.33]
 [0.12 0.8  0.59 0.29 0.21]
 [0.57 0.72 0.29 0.54 0.58]]


** Exercise 5 : Indexing Arrays**

In [11]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array[1,:])

[20 21 22 23 24]


**Exercise 6 : Reversing elements**

In [19]:
print(arr1)
reversed_arr = arr1[::-1]
print(reversed_arr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


**Exercise 7 : Identity Matrix**

In [20]:
print("4x4 identity:")
print(np.eye(4))
print()

4x4 identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



**Exercise 8 : Simple Aggregate Funcs**

In [22]:
print(arr1)
sum_arr = np.sum(arr1)
print(f"sum: {sum_arr}")
av_arr = np.mean(arr1)
print(f"average: {av_arr}")

[0 1 2 3 4 5 6 7 8 9]
sum: 45
average: 4.5


**Exercise 9 : Create Array and Change its Structure**

In [28]:
arr5 = np.arange(1,21).reshape(4,5)
print(arr5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**Exercise 9 : Create Array and Change its Structure**

In [33]:
print(arr1)
odd_numbers = arr1[arr1 % 2 != 0]
print(odd_numbers)


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
